### ISSUE TITLE
steps to run app

### ISSUE THREAD

**Issue by Muneera-Salah** [winar-jin/studentEvaluateSystem#1]
Hi kindly provided me steps to run the app. thank you

**Comment by winar-jin** [comment]
First, thank you for your attention to this project, and really sorry that you can't run this app by this project's readme file. I am sorry for that, and I will try to explain it to you, hope it can help you.

Basically, this project uses Laravel 5 framework. And you can refer to the official website of Laravel 5 to check the documentation about the installation and other help. [https://laravel.com/docs/5.8/installation](https://laravel.com/docs/5.8/installation)

And in a word, it mainly contains these steps:
* Use Composer to install the laravel dependency: `composer global require laravel/installer`
* After installation, you can use `laravel --help` to check whether your installation is successful.
* Then you have to install Nginx Server.  [https://docs.nginx.com/nginx/admin-guide/installing-nginx/installing-nginx-open-source/](https://docs.nginx.com/nginx/admin-guide/installing-nginx/installing-nginx-open-source/)
* Go to `/etc/nginx/conf.d` and add a new Nginx config file, such as `laravel.dev.conf` and paste next code to this file:
```
server {
  listen        80;
  server_name   www.example.com; # replact this with your own domain or just make it empty and use localhost to access it
  root          ./location_of_this_project/public; # replace ./location_of_this_project to the real location 
  index         index.php index.html index.htm;

  location / {
    index  index.php index.html index.htm;
    try_files $uri @rewrite;
  }

  location @rewrite {
    rewrite ^ /index.php;
  }

  location ~ \.php$ {
    fastcgi_pass 127.0.0.1:9000;
    fastcgi_index index.php;
    include fastcgi.conf;
  }

}
``` 
* Then you can go to visit `http://www.example.com` or `http://localhost` to see this website.

At last, what I want to say is that this project has time not to maintain, So I suggest you just make this project as a reference.

Thank you, If you got any questions, feel free to leave a message.

**Comment by Muneera-Salah** [comment]
ok Thanks  a lot
